# Generated by Django 4.2.4 on 2024-09-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0009_alter_members_quota_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersDpi',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.members',),
        ),
        migrations.CreateModel(
            name='MembersStarlink',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.members',),
        ),
    ]
