# Generated by Django 5.2.17 on 2026-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_lookup_name_unique'),
        ('networks', '0002_networksgroup_networks_network_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksgroup',
            name='member_sites',
            field=models.ManyToManyField(blank=True, related_name='network_groups', to='members.members', verbose_name='Member Sites'),
        ),
    ]
