# Generated by Django 4.2.4 on 2024-02-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Member Name')),
                ('member_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Member Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('member_id', models.CharField(max_length=50, unique=True, verbose_name='Member ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('online_at', models.DateField(blank=True, null=True, verbose_name='Start Online')),
                ('offline_at', models.DateTimeField(blank=True, null=True, verbose_name='Stop Online')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
    ]
