# Generated by Django 4.2.4 on 2024-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='upload_baa',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
