# Generated by Django 4.2.4 on 2024-02-28 08:38

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('members', '0003_alter_members_upload_baa'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='links',
            field=modelcluster.fields.ParentalManyToManyField(related_name='members', to='links.links'),
        ),
    ]
