# Generated by Django 4.2.4 on 2024-03-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
