# Generated by Django 4.2.11 on 2024-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_members_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='service_line',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Service Line'),
        ),
    ]
