# Generated by Django 4.2.4 on 2024-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_members_service_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='quota_string',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quota'),
        ),
    ]
