# Generated by Django 4.2.4 on 2024-09-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_members_quota_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='quota_string',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quota Info'),
        ),
    ]
