# Generated by Django 4.2.4 on 2024-09-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_members_quota_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
    ]
