# Generated by Django 5.2.17 on 2026-09-08 09:05

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_links_options'),
        ('members', '0010_alter_members_options'),
        ('networks', '0002_networksgroup_networks_network_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='baa_status_category',
            field=models.CharField(blank=True, choices=[('New Link', 'New Link'), ('Upgrade Link', 'Upgrade Link'), ('Downgrade Link', 'Downgrade Link'), ('Relokasi', 'Relokasi')], max_length=20, null=True, verbose_name='BAA Status Category'),
        ),
        migrations.AddField(
            model_name='members',
            name='bap_file',
            field=models.FileField(blank=True, null=True, upload_to='bap/', verbose_name='BAP Dismantle'),
        ),
        migrations.AddField(
            model_name='members',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoice/', verbose_name='Invoice File'),
        ),
        migrations.AddField(
            model_name='members',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='members',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Manual Site'),
        ),
        migrations.AddField(
            model_name='members',
            name='po_file_user',
            field=models.FileField(blank=True, null=True, upload_to='po/', verbose_name='PO from User'),
        ),
        migrations.AddField(
            model_name='members',
            name='po_file_vendor',
            field=models.FileField(blank=True, null=True, upload_to='po/', verbose_name='PO to Vendor'),
        ),
        migrations.AddField(
            model_name='members',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Number'),
        ),
        migrations.AddField(
            model_name='members',
            name='sdwan_package',
            field=models.CharField(blank=True, choices=[('BackOne - SDWAN Lite', 'BackOne - SDWAN Lite'), ('BackOne - SDWAN Pro', 'BackOne - SDWAN Pro'), ('BackOne - SDWAN Gateway', 'BackOne - SDWAN Gateway'), ('BackOne - Tanpa SDWAN', 'BackOne - Tanpa SDWAN')], max_length=30, null=True, verbose_name='SDWAN Package'),
        ),
        migrations.AlterField(
            model_name='members',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.networks', verbose_name='Network'),
        ),
        migrations.CreateModel(
            name='MemberLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MAIN', 'MAIN'), ('BACKUP', 'BACKUP'), ('SINGLE', 'SINGLE')], default='MAIN', max_length=10, verbose_name='Link Role')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provider')),
                ('capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Capacity')),
                ('sid', models.CharField(blank=True, max_length=100, null=True, verbose_name='SID Langganan')),
                ('member', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='members.members')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.links', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Member Link',
                'verbose_name_plural': 'Member Links',
                'db_table': 'members_link',
            },
        ),
    ]
