# Generated by Django 5.2.17 on 2026-09-09 10:21

import django.db.models.deletion
from django.db import migrations, models


def seed_lookup_tables(apps, schema_editor):
    """Seed the three lookup tables (C26). get_or_create so re-runs are idempotent."""
    SdwanPackage = apps.get_model("members", "SdwanPackage")
    BaaStatus = apps.get_model("members", "BaaStatus")
    LinkRole = apps.get_model("members", "LinkRole")

    for name in [
        "BackOne - SDWAN Lite",
        "BackOne - SDWAN Pro",
        "BackOne - SDWAN Gateway",
        "BackOne - Tanpa SDWAN",
    ]:
        SdwanPackage.objects.get_or_create(name=name)

    for name in ["New Link", "Upgrade Link", "Downgrade Link", "Relokasi"]:
        BaaStatus.objects.get_or_create(name=name)

    for name in ["MAIN", "BACKUP", "SINGLE"]:
        LinkRole.objects.get_or_create(name=name)


def backfill_to_fk(apps, schema_editor):
    """Map each existing CharField string value to its seeded lookup row PK (C26/V34).

    Prod has only `BackOne - SDWAN Pro`, `New Link`, `BACKUP`; but seed covers all
    known values so any present value maps. Unknown values (not in seed) are left
    NULL rather than dropped — preserving the data and keeping FK integrity.
    """
    Members = apps.get_model("members", "Members")
    MemberLink = apps.get_model("members", "MemberLink")
    SdwanPackage = apps.get_model("members", "SdwanPackage")
    BaaStatus = apps.get_model("members", "BaaStatus")
    LinkRole = apps.get_model("members", "LinkRole")

    sdwan_map = {s.name: s.pk for s in SdwanPackage.objects.all()}
    baa_map = {b.name: b.pk for b in BaaStatus.objects.all()}
    role_map = {r.name: r.pk for r in LinkRole.objects.all()}

    for m in Members.objects.all():
        sdwan_pk = sdwan_map.get(m.sdwan_package)
        baa_pk = baa_map.get(m.baa_status_category)
        # Column is still the CharField here (AlterField runs after); store the
        # lookup PK as a numeric string. The char→FK ALTER then coerces to int.
        Members.objects.filter(pk=m.pk).update(
            sdwan_package=str(sdwan_pk) if sdwan_pk else None,
            baa_status_category=str(baa_pk) if baa_pk else None,
        )

    for ml in MemberLink.objects.all():
        role_pk = role_map.get(ml.role)
        MemberLink.objects.filter(pk=ml.pk).update(
            role=str(role_pk) if role_pk else None,
        )


def backfill_to_string(apps, schema_editor):
    """Reverse: convert FK back to stored string value (denormalize, for reverse migrate)."""
    Members = apps.get_model("members", "Members")
    MemberLink = apps.get_model("members", "MemberLink")
    SdwanPackage = apps.get_model("members", "SdwanPackage")
    BaaStatus = apps.get_model("members", "BaaStatus")
    LinkRole = apps.get_model("members", "LinkRole")

    sdwan_map = {s.pk: s.name for s in SdwanPackage.objects.all()}
    baa_map = {b.pk: b.name for b in BaaStatus.objects.all()}
    role_map = {r.pk: r.name for r in LinkRole.objects.all()}

    for m in Members.objects.all():
        # Reverse ordering: AlterField FK→Char already ran, so the char column
        # holds the FK id as a string. Map that id back to the lookup name.
        try:
            sdwan_name = sdwan_map.get(int(m.sdwan_package)) if m.sdwan_package else ""
        except (ValueError, TypeError):
            sdwan_name = m.sdwan_package or ""
        try:
            baa_name = baa_map.get(int(m.baa_status_category)) if m.baa_status_category else ""
        except (ValueError, TypeError):
            baa_name = m.baa_status_category or ""
        Members.objects.filter(pk=m.pk).update(
            sdwan_package=sdwan_name,
            baa_status_category=baa_name,
        )

    for ml in MemberLink.objects.all():
        try:
            role_name = role_map.get(int(ml.role)) if ml.role else ""
        except (ValueError, TypeError):
            role_name = ml.role or ""
        MemberLink.objects.filter(pk=ml.pk).update(role=role_name)




class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_members_baa_status_category_members_bap_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BAA Status',
                'verbose_name_plural': 'BAA Statuses',
            },
        ),
        migrations.CreateModel(
            name='LinkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link Role',
                'verbose_name_plural': 'Link Roles',
            },
        ),
        migrations.CreateModel(
            name='SdwanPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SDWAN Package',
                'verbose_name_plural': 'SDWAN Packages',
            },
        ),
        migrations.RunPython(seed_lookup_tables, migrations.RunPython.noop),
        migrations.RunPython(backfill_to_fk, backfill_to_string),
        migrations.AlterField(
            model_name='members',
            name='baa_status_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.baastatus', verbose_name='BAA Status Category'),
        ),
        migrations.AlterField(
            model_name='memberlink',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_links', to='members.linkrole', verbose_name='Link Role'),
        ),
        migrations.AlterField(
            model_name='members',
            name='sdwan_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.sdwanpackage', verbose_name='SDWAN Package'),
        ),
    ]
