# Generated by Django 5.2.17 on 2026-09-09
# DB-level unique on lookup `name` so SlugRelatedField never sees
# MultipleObjectsReturned (V38). No data migration needed — prod rows are
# already distinct (C26); duplicates would be a data bug, not ours to merge.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_baastatus_linkrole_sdwanpackage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sdwanpackage",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="baastatus",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="linkrole",
            name="name",
            field=models.CharField(max_length=10, unique=True, verbose_name="Name"),
        ),
    ]
